#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
#                     TAVANA - Release Build Monitor
# ═══════════════════════════════════════════════════════════════════════════════
# Monitor the v1.0.0 release build progress
# ═══════════════════════════════════════════════════════════════════════════════

set -e

VERSION="${1:-v1.0.0}"

echo "═══════════════════════════════════════════════════════════════════════════"
echo "                    🔍 MONITORING RELEASE BUILD: $VERSION"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "GitHub Actions: https://github.com/Angelerator/Tavana/actions"
echo ""
echo "Expected duration: ~30-45 minutes"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "                    📊 BUILD PROGRESS CHECKLIST"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "Phase 1: Build & Push Images (30-40 min)"
echo "  ⏳ Checkout code"
echo "  ⏳ Set up QEMU (for multi-arch)"
echo "  ⏳ Set up Docker Buildx"
echo "  ⏳ Login to Docker Hub"
echo "  ⏳ Login to GHCR"
echo "  ⏳ Extract metadata"
echo "  ⏳ Build Gateway (linux/amd64, linux/arm64)"
echo "  ⏳ Push Gateway to Docker Hub"
echo "  ⏳ Push Gateway to GHCR"
echo "  ⏳ Sign Gateway with Cosign"
echo "  ⏳ Build Worker (linux/amd64, linux/arm64)"
echo "  ⏳ Push Worker to Docker Hub"
echo "  ⏳ Push Worker to GHCR"
echo "  ⏳ Sign Worker with Cosign"
echo ""
echo "Phase 2: Package & Publish Helm (2 min)"
echo "  ⏳ Install Helm"
echo "  ⏳ Update Chart.yaml version"
echo "  ⏳ Package Helm chart"
echo "  ⏳ Push to GHCR OCI registry"
echo ""
echo "Phase 3: Create GitHub Release (1 min)"
echo "  ⏳ Generate release notes"
echo "  ⏳ Create release"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "TO CHECK BUILD STATUS:"
echo ""
echo "  # Via browser"
echo "  open https://github.com/Angelerator/Tavana/actions"
echo ""
echo "  # Via GitHub CLI (if installed)"
echo "  gh run list --limit 1"
echo "  gh run watch"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "                    ✅ WHAT TO CHECK AFTER BUILD COMPLETES"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Docker Hub Images:"
echo "   https://hub.docker.com/r/tavana/gateway/tags"
echo "   https://hub.docker.com/r/tavana/worker/tags"
echo ""
echo "2. GHCR Images:"
echo "   https://github.com/Angelerator/Tavana/pkgs/container/tavana-gateway"
echo "   https://github.com/Angelerator/Tavana/pkgs/container/tavana-worker"
echo ""
echo "3. Helm Chart:"
echo "   https://github.com/Angelerator/Tavana/pkgs/container/charts%2Ftavana"
echo ""
echo "4. GitHub Release:"
echo "   https://github.com/Angelerator/Tavana/releases/tag/$VERSION"
echo ""
echo "5. Test pulling images:"
echo ""
echo "   docker pull tavana/gateway:$VERSION"
echo "   docker pull tavana/worker:$VERSION"
echo "   docker pull ghcr.io/angelerator/tavana-gateway:$VERSION"
echo "   docker pull ghcr.io/angelerator/tavana-worker:$VERSION"
echo ""
echo "6. Test pulling Helm chart:"
echo ""
echo "   helm pull oci://ghcr.io/angelerator/charts/tavana --version ${VERSION#v}"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "When build completes, run:"
echo ""
echo "  ./test-deployment.sh"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"

