//! Generated protobuf and gRPC code
//!
//! This module includes the auto-generated code from proto files.
//! The files are generated by tonic-build during compilation.

// Include generated proto code if it exists
// Run `cargo build` to generate these files from proto definitions

#[path = ""]
mod generated {
    #[allow(clippy::all)]
    #[allow(missing_docs)]
    #[allow(unused_imports)]
    pub mod tavana_v1 {
        tonic::include_proto!("tavana.v1");
    }
}

// Re-export for convenience
pub use generated::tavana_v1::*;
